apiVersion: v1
kind: Pod
metadata:
  name: roko-secret
spec:
  containers:
  - name: envars-test-container
    image: registry.gitlab.com/datenn/main/backend-web-client/backend-web-app:v0.0.87
    envFrom:
    - secretRef:
        name: web-api-secrets
    envFrom:
    - configMapRef:
        name: web-api-config
  imagePullSecrets:
  - name: registry-secret-worker
  
    
