apiVersion: v1
kind: Pod
metadata:
  name: roko-secret
spec:
  containers:
  - name: envars-test-container
    image: registry.gitlab.com/datenn/main/backend-web-client/backend-web-app:v0.0.87
    envFrom:
    - secretRef:
        name: workers-secret
  imagePullSecrets:
  - name: registry-secret-worker
    
