apiVersion: v1
kind: Pod
metadata:
  name: roko-secret
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - secretRef:
        name: web-api-secrets
    #envFrom:
    - configMapRef:
        name: web-api-config
  #imagePullSecrets:
  #- name: registry-secret-worker
    
