apiVersion: v1
kind: Pod
metadata:
  name: roko-secret
spec:
  containers:
  - name: envars-test-container
    image: nginx
    envFrom:
    - secretRef:
        name: workers-secret
    envFrom:
    - config_map_ref:
        name: workers-config
