apiVersion: v1
kind: Pod
metadata:
  name: roko-secret
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: DB_PWD
      valueFrom:
        secretKeyRef:
          name: web-api-secrets
          key: DB_PWD
    envFrom:
    - configMapRef:
        name: web-api-config
  #imagePullSecrets:
  #- name: registry-secret-worker
    
