### ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    creationTimestamp: null
    name: dev-expansion-aws-datenn-eks-alb-controller
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: dev-expansion-aws-datenn-eks-alb-controller
subjects:
- kind: ServiceAccount
  name: dev-expansion-aws-datenn-eks-alb-controller
  namespace: kube-system
---
### ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
    creationTimestamp: null
    name: dev-expansion-aws-datenn-eks-alb-controller
    namespace: kube-system
    

